version: "3.3"

services:
  keycloak:
    image: kctest:latest
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "1234"
      DEBUG: "true"
      DEBUG_PORT: "*:8787"
      KEYCLOAK_IMPORT: "/opt/jboss/realm.json"
    ports:
    - 8080:8080
    - 5005:8787
    volumes:
    - ./target/libs/ageValidator-1.0.jar:/opt/jboss/keycloak/standalone/deployments/ageValidator-1.0.jar
    - ./realm.json:/opt/jboss/realm.json

